### ISSUE TITLE
error: no viable conversion from 'QLatin1String' to 'const QKeySequence' on MacOS 10.13

### ISSUE THREAD

**Issue by pp611** [pgmodeler/pgmodeler#1043]
Build failed with the message above: PostgreSQL 10.1 and qt 5.10, both installed with brew., xcode 9.2.
 
pgmodeler.pri is updated with

```
macx {
  PGSQL_LIB = /usr/local/lib//libpq.dylib
  PGSQL_INC = /usr/local/include/
  XML_INC = /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2
  XML_LIB = /usr/lib/libxml2.dylib
  INCLUDEPATH += $$PGSQL_INC $$XML_INC
}
```

Full error message:

```
In file included from src/mainwindow.cpp:23:
In file included from src/sqlexecutionwidget.h:28:
src/ui_sqlexecutionwidget.h:186:34: error: no viable conversion from 'QLatin1String' to 'const QKeySequence'
        snippets_tb->setShortcut(QLatin1String("Alt+X"));
                                 ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:157:5: note: candidate constructor not viable:
      no known conversion from 'QLatin1String' to 'const QString &' for 1st argument
    QKeySequence(const QString &key, SequenceFormat format = NativeText);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:158:5: note: candidate constructor not viable:
      no known conversion from 'QLatin1String' to 'int' for 1st argument
    QKeySequence(int k1, int k2 = 0, int k3 = 0, int k4 = 0);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:159:5: note: candidate constructor not viable:
      no known conversion from 'QLatin1String' to 'const QKeySequence &' for 1st argument
    QKeySequence(const QKeySequence &ks);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:160:5: note: candidate constructor not viable:
      no known conversion from 'QLatin1String' to 'QKeySequence::StandardKey' for 1st argument
    QKeySequence(StandardKey key);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtWidgets.framework/Headers/qabstractbutton.h:87:42: note: passing argument to
      parameter 'key' here
    void setShortcut(const QKeySequence &key);
```

**Comment by marchaase** [comment]
I am also having a similar error building from source on Mac OSX.

Installed PostgreSQL and QT with Brew:
`
brew info postgresql
postgresql: stable 10.1 (bottled), HEAD

brew info qt
qt: stable 5.10.0 (bottled), HEAD [keg-only]
`

pgmodeler commit at:
`
commit ea8b42a3fc8b4284fe4348f7457bb4c04599ae41 (HEAD -> develop, origin/develop, origin/HEAD)
`

Getting the following error:
`
In file included from src/mainwindow.cpp:23:
In file included from src/sqlexecutionwidget.h:28:
src/ui_sqlexecutionwidget.h:186:34: error: no viable conversion from 'QLatin1String' to 'const QKeySequence'
        snippets_tb->setShortcut(QLatin1String("Alt+X"));
                                 ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:157:5: note: candidate constructor not viable: no known conversion from 'QLatin1String' to 'const QString &' for 1st argument
    QKeySequence(const QString &key, SequenceFormat format = NativeText);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:158:5: note: candidate constructor not viable: no known conversion from 'QLatin1String' to 'int' for 1st argument
    QKeySequence(int k1, int k2 = 0, int k3 = 0, int k4 = 0);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:159:5: note: candidate constructor not viable: no known conversion from 'QLatin1String' to 'const QKeySequence &' for 1st argument
    QKeySequence(const QKeySequence &ks);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:160:5: note: candidate constructor not viable: no known conversion from 'QLatin1String' to 'QKeySequence::StandardKey' for 1st argument
    QKeySequence(StandardKey key);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtWidgets.framework/Headers/qabstractbutton.h:87:42: note: passing argument to parameter 'key' here
    void setShortcut(const QKeySequence &key);
                                         ^
In file included from src/mainwindow.cpp:23:
In file included from src/sqlexecutionwidget.h:28:
src/ui_sqlexecutionwidget.h:204:32: error: no viable conversion from 'QLatin1String' to 'const QKeySequence'
        export_tb->setShortcut(QLatin1String("Alt+X"));
                               ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:157:5: note: candidate constructor not viable: no known conversion from 'QLatin1String' to 'const QString &' for 1st argument
    QKeySequence(const QString &key, SequenceFormat format = NativeText);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:158:5: note: candidate constructor not viable: no known conversion from 'QLatin1String' to 'int' for 1st argument
    QKeySequence(int k1, int k2 = 0, int k3 = 0, int k4 = 0);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:159:5: note: candidate constructor not viable: no known conversion from 'QLatin1String' to 'const QKeySequence &' for 1st argument
    QKeySequence(const QKeySequence &ks);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtGui.framework/Headers/qkeysequence.h:160:5: note: candidate constructor not viable: no known conversion from 'QLatin1String' to 'QKeySequence::StandardKey' for 1st argument
    QKeySequence(StandardKey key);
    ^
/usr/local/Cellar/qt/5.10.0_1/lib/QtWidgets.framework/Headers/qabstractbutton.h:87:42: note: passing argument to parameter 'key' here
    void setShortcut(const QKeySequence &key);
                                         ^
2 errors generated.
`

**Comment by marchaase** [comment]
I was able to get it to compile by applying the following patch:
```
diff --git a/libpgmodeler_ui/ui/sqlexecutionwidget.ui b/libpgmodeler_ui/ui/sqlexecutionwidget.ui
index 18680855..0611a0c0 100644
--- a/libpgmodeler_ui/ui/sqlexecutionwidget.ui
+++ b/libpgmodeler_ui/ui/sqlexecutionwidget.ui
@@ -316,7 +316,7 @@
         </size>
        </property>
        <property name="shortcut">
-        <string notr="true">Alt+X</string>
+        <string>Alt+X</string>
        </property>
        <property name="checkable">
         <bool>false</bool>
@@ -360,7 +360,7 @@
         </size>
        </property>
        <property name="shortcut">
-        <string notr="true">Alt+X</string>
+        <string>Alt+X</string>
        </property>
        <property name="checkable">
         <bool>false</bool>
```

**Comment by heisian** [comment]
@marchaase @rkhaotix could this be made into a PR?

**Comment by rkhaotix** [comment]
This issue is already fixed in the current codebase (branches 0.9.1-beta1 and rls-support) :)

**Comment by heisian** [comment]
got it, thanks!

**Comment by joris255** [comment]
hmmm... I still got the issue on rls-support. :-/ 
the commit `309be58b` did not fix it entirely? 

Is it just me?

```
In file included from src/mainwindow.cpp:23:
In file included from src/sqlexecutionwidget.h:28:
src/ui_sqlexecutionwidget.h:142:30: error: no viable conversion from 'QLatin1String' to 'const QKeySequence'
        find_tb->setShortcut(QLatin1String(""));
                             ^~~~~~~~~~~~~~~~~
../../../Qt/5.10.1/clang_64/lib/QtGui.framework/Headers/qkeysequence.h:157:5: note: candidate constructor not viable: no known conversion
      from 'QLatin1String' to 'const QString &' for 1st argument
    QKeySequence(const QString &key, SequenceFormat format = NativeText);
    ^
../../../Qt/5.10.1/clang_64/lib/QtGui.framework/Headers/qkeysequence.h:158:5: note: candidate constructor not viable: no known conversion
      from 'QLatin1String' to 'int' for 1st argument
    QKeySequence(int k1, int k2 = 0, int k3 = 0, int k4 = 0);
    ^
../../../Qt/5.10.1/clang_64/lib/QtGui.framework/Headers/qkeysequence.h:159:5: note: candidate constructor not viable: no known conversion
      from 'QLatin1String' to 'const QKeySequence &' for 1st argument
    QKeySequence(const QKeySequence &ks);
    ^
../../../Qt/5.10.1/clang_64/lib/QtGui.framework/Headers/qkeysequence.h:160:5: note: candidate constructor not viable: no known conversion
      from 'QLatin1String' to 'QKeySequence::StandardKey' for 1st argument
    QKeySequence(StandardKey key);
    ^
/Users/fx/Qt/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qabstractbutton.h:87:42: note: passing argument to parameter 'key' here
    void setShortcut(const QKeySequence &key);
                                         ^
1 error generated.
make[1]: *** [obj/mainwindow.o] Error 1
make: *** [sub-libpgmodeler_ui-make_first-ordered] Error 2
```

**Comment by joris255** [comment]
fixed with this patch:

diff --git a/libpgmodeler_ui/ui/sqlexecutionwidget.ui b/libpgmodeler_ui/ui/sqlexecutionwidget.ui
index bc63f4f..42fdf5c 100644
--- a/libpgmodeler_ui/ui/sqlexecutionwidget.ui
+++ b/libpgmodeler_ui/ui/sqlexecutionwidget.ui
@@ -199,7 +199,7 @@
         </size>
        </property>
        <property name="shortcut">
-        <string notr="true"/>
+        <string>Ctrl+S</string>
        </property>
        <property name="checkable">
         <bool>true</bool>

**Comment by rkhaotix** [comment]
Try again now with the branch "minor-fixes".

**Comment by joris255** [comment]
Thanks!
